blueprint:
  name: Heizungshauptschalter Schedule
  description: 'Heizungshauptschalter zeitbasiert an und aus schalten'
  domain: automation
  input:
    entity_switch:
      name: Heizungshauptschalter
      selector:
        entity:
          domain: switch
    entity_schedule:
      name: Heizungsplan
      selector:
        entity:
          domain: schedule
    entity_condition:
      name: Heizungsmodus
      selector:
        entity:
          domain: input_select
mode: restart
max_exceeded: silent
variables:
  entity_switch: !input 'entity_switch'
  entity_schedule: !input 'entity_schedule'
  entity_condition: !input 'entity_condition'
trigger:
  - platform: state
    entity_id: !input 'entity_condition'
  - platform: state
    entity_id: !input 'entity_schedule'
condition:
  - condition: state
    entity_id: !input 'entity_condition'
    state: Zeitbasiert
  - condition: template
    value_template: '{{ states(entity_Heizungshauptschalter) != states(entity_schedule) }}'
action:
  - service: homeassistant.turn_{{ states(entity_schedule) }}
    data:
      entity_id: '{{ entity_Heizungshauptschalter }}'
