blueprint:
  name: Heizungshauptschalter Schedule
  description: 'Heizungshauptschalter zeitbasiert an und aus schalten'
  domain: automation
  input:
    entity_Heizungshauptschalter:
      name: Entity für Heizungshauptschalter
      selector:
        entity:
    entity_schedule:
      name: Schedule
      selector:
        entity:
mode: restart
max_exceeded: silent
variables:
  entity_Heizungshauptschalter: !input 'entity_Heizungshauptschalter'
  entity_schedule: !input 'entity_schedule'
trigger:
  - platform: state
    entity_id: !input 'entity_Heizungshauptschalter'
  - platform: state
    entity_id: !input 'entity_schedule'
condition:
  - condition: template
    value_template: '{{ states(entity_Heizungshauptschalter) != states(entity_schedule) }}'
action:
  - service: homeassistant.turn_{{ trigger.to_state.state }}
    data:
      entity_id: '{% if trigger.from_state.entity_id == entity_Heizungshauptschalter %} {{ entity_schedule }} {% else %} {{ entity_Heizungshauptschalter }} {% endif %}'
